/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#1f2a3b',
        'surface-bright': '#f8f9fb',
        'secondary-container': '#fd8b00',
        'on-secondary-container': '#603100',
        'on-primary': '#ffffff',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'primary-container': '#1a2b3c',
        'surface-container-high': '#e6e8ea',
        outline: '#74777d',
        'inverse-on-surface': '#eff1f3',
        background: '#f8f9fb',
        primary: '#041627',
        'outline-variant': '#c4c6cd',
        'secondary-fixed': '#ffdcc3',
        surface: '#f8f9fb',
        'on-tertiary-container': '#8691a6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#111c2c',
        'inverse-surface': '#2d3133',
        'on-secondary-fixed': '#2f1500',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed-variant': '#3c475a',
        tertiary: '#0a1526',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#d8e3fa',
        'on-primary-container': '#8192a7',
        'primary-fixed': '#d2e4fb',
        'tertiary-fixed-dim': '#bcc7dd',
        'primary-fixed-dim': '#b7c8de',
        'on-primary-fixed-variant': '#38485a',
        'inverse-primary': '#b7c8de',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'on-surface-variant': '#44474c',
        error: '#ba1a1a',
        // Semáforo de avance contra el tiempo estándar (ver utils/workProgress.js). No se
        // reutiliza `secondary` para el ámbar: ese naranja ya significa "acción del asesor" en
        // la UI, y mezclarlo con una alerta de tiempo haría ambiguo el color.
        'progress-ok': '#1b7f3b',
        'progress-warn': '#b8860b',
        'surface-dim': '#d8dadc',
        'on-secondary-fixed-variant': '#6e3900',
        secondary: '#904d00',
        'surface-tint': '#4f6073',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#0b1d2d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        base: '8px',
        'card-padding': '24px',
        'container-max': '1440px',
        gutter: '24px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['"JetBrains Mono"', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
